/* kernel/jack/jack_mount.c - generated by tools/embed_vm.py */
#include "jack_data.h"
#include "vm_store.h"
void jack_data_mount(void) {
    vm_store_clear();
    for (int i = 0; jack_data_table[i].name; i++) {
        const JackDataEntry *e = &jack_data_table[i];
        vm_store_add(e->name, e->data, e->size);
    }
}
